//
// Copyright (C) 2021 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

= Attributions

:retrieval_date: 2021-10-27

== OpenSSL

:my_link: pass:n[link:https://www.openssl.org/[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
OpenSSL is a robust, commercial-grade, and full-featured toolkit for the
Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols.
It is also a general-purpose cryptography library.

++[++...]

OpenSSL is licensed under an Apache-style license, which basically means
that you are free to get and use it for commercial and non-commercial
purposes subject to some simple license conditions.
____

ifdef::env-github[]
{nbsp}
endif::[]

:my_link: pass:n[link:https://www.openssl.org/source/license.html[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
OpenSSL is covered by one of two licenses, depending on which release is
involved. In all cases, there is a file named LICENSE in the top-level
of the release. Copies can also be found here.

For the 3.0 release, and later releases derived from that,
link:https://www.openssl.org/source/apache-license-2.0.txt[the Apache License v2]
applies. This also applies to the git "master" branch.

For any release made before OpenSSL 3.0 (namely the 1.1.1, 1.1.0, 1.0.2,
and all prior releases including those not currently supported),
link:https://www.openssl.org/source/license-openssl-ssleay.txt[the dual OpenSSL and SSLeay license]
applies. Note that this is also true for any updates to those releases
-- the "letter suffix" -- no matter when they are made. It also applies
to the git branches for all those releases, and to any public forks that
have not rebased to master (or 3.0).
____

== GMP

:my_link: pass:n[link:https://gmplib.org/[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
GMP is a free library for arbitrary precision arithmetic, operating on
signed integers, rational numbers, and floating-point numbers. There is
no practical limit to the precision except the ones implied by the
available memory in the machine GMP runs on. GMP has a rich set of
functions, and the functions have a regular interface.

++[++...]

Since version 6, GMP is distributed under the dual licenses,
link:https://www.gnu.org/licenses/lgpl.html[GNU LGPL v3]
and
link:https://www.gnu.org/licenses/gpl-2.0.html[GNU GPL v2].
These licenses make the library free to use, share, and improve, and
allow you to pass on the result. The GNU licenses give freedoms, but
also set firm restrictions on the use with non-free programs.
____

== Nettle

:my_link: pass:n[link:https://www.lysator.liu.se/~nisse/nettle/[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
Nettle is a cryptographic library that is designed to fit easily in more
or less any context: In crypto toolkits for object-oriented languages
({cpp}, Python, Pike, ...), in applications like LSH or GNUPG, or even
in kernel space.
____

ifdef::env-github[]
{nbsp}
endif::[]

:my_link: pass:n[link:https://www.lysator.liu.se/~nisse/nettle/nettle.html[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
Nettle is dual licenced under the
link:https://www.gnu.org/licenses/gpl-2.0.html[GNU General Public License version 2]
or later, and the
link:https://www.gnu.org/licenses/lgpl.html[GNU Lesser General Public License version 3]
or later. When using Nettle, you must comply fully with all conditions
of at least one of these licenses. A few of the individual files are
licensed under more permissive terms, or in the public domain. To find
the current status of particular files, you have to read the copyright
notices at the top of the files.
____

== RabbitMQ C Client

:my_link: pass:n[link:https://github.com/alanxz/rabbitmq-c[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
This is a C-language AMQP client library for use with v2.0+ of the
link:http://www.rabbitmq.com/[RabbitMQ] broker.
____

ifdef::env-github[]
{nbsp}
endif::[]

:my_link: pass:n[link:https://github.com/alanxz/rabbitmq-c/blob/master/LICENSE[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
[listing]
----
MIT License

Copyright (c) 2012-2021 Alan Antonuk

Copyright (c) 2007-2012 VMware, Inc.

Copyright (c) 2009-2010 VMware, Inc. and Tony Garnock-Jones

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use, copy,
modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
----
____

== RabbitMQ Java Client

:my_link: pass:n[link:https://www.rabbitmq.com/java-client.html[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
The RabbitMQ Java client library allows Java and JVM-based applications
to connect to and interact with RabbitMQ nodes.

++[++...]

The library is
link:https://github.com/rabbitmq/rabbitmq-java-client/[open-source],
and is triple-licensed under

* link:https://www.apache.org/licenses/LICENSE-2.0.html[Apache Public License 2.0]
* link:https://www.mozilla.org/MPL/2.0/[Mozilla Public License 2.0]
* link:https://www.gnu.org/licenses/gpl-2.0.html[GPL 2.0]
____

== LLVM

:my_link: pass:n[link:https://llvm.org/[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
The LLVM Project is a collection of modular and reusable compiler and
toolchain technologies. Despite its name, LLVM has little to do with
traditional virtual machines. The name "LLVM" itself is not an acronym;
it is the full name of the project.
____

ifdef::env-github[]
{nbsp}
endif::[]

:my_link: pass:n[link:https://llvm.org/docs/DeveloperPolicy.html[]]
[quote, Retrieved from {my_link} on {retrieval_date}]
____
Contributions to LLVM are licensed under the
link:https://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0],
with two limited exceptions intended to ensure that LLVM is very
permissively licensed. Collectively, the name of this license is "Apache
2.0 License with LLVM exceptions". The exceptions read:

[listing]
----
---- LLVM Exceptions to the Apache 2.0 License ----

As an exception, if, as a result of your compiling your source code, portions
of this Software are embedded into an Object form of such source code, you
may redistribute such embedded portions in such Object form without complying
with the conditions of Sections 4(a), 4(b) and 4(d) of the License.

In addition, if you combine or link compiled forms of this Software with
software that is licensed under the GPLv2 ("Combined Software") and if a
court of competent jurisdiction determines that the patent provision (Section
3), the indemnity provision (Section 9) or other Section of the License
conflicts with the conditions of the GPLv2, you may retroactively and
prospectively choose to deem waived or otherwise exclude such Section(s) of
the License, but only in their entirety and only with respect to the Combined
Software.
----

We intend to keep LLVM perpetually open source and available under a
permissive license - this fosters the widest adoption of LLVM by
allowing commercial products to be derived from LLVM with few
restrictions and without a requirement for making any derived works also
open source. In particular, LLVM's license is not a "copyleft" license
like the GPL.

The "Apache 2.0 License with LLVM exceptions" allows you to:

* freely download and use LLVM (in whole or in part) for personal,
internal, or commercial purposes.

* include LLVM in packages or distributions you create.

* combine LLVM with code licensed under every other major open source
license (including BSD, MIT, GPLv2, GPLv3...).

* make changes to LLVM code without being required to contribute it back to the project - contributions are appreciated though!

However, it imposes these limitations on you:

* You must retain the copyright notice if you redistribute LLVM: You
cannot strip the copyright headers off or replace them with your own.

* Binaries that include LLVM must reproduce the copyright notice (e.g.
in an included README file or in an "About" box), unless the LLVM code
was added as a by-product of compilation. For example, if an LLVM
runtime library like compiler_rt or libc++ was automatically included
into your application by the compiler, you do not need to attribute it.

* You can't use our names to promote your products
(LLVM derived or not) - though you can make truthful statements about
your use of the LLVM code, without implying our sponsorship.

* There's no warranty on LLVM at all.

We want LLVM code to be widely used, and believe that this provides a
model that is great for contributors and users of the project. For more
information about the Apache 2.0 License, please see the
link:http://www.apache.org/foundation/license-faq.html[Apache License FAQ],
maintained by the Apache Project.
____

//
