#
# Copyright (C) 2021 Stealth Software Technologies, Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

#
# sst_ajh_c_cpp_test <dir> <lib>...
#

sst_ajh_c_cpp_test() {

  local dir
  local libs
  local x1
  local x2
  local x3

  sst_expect_argument_count $# 2-

  dir=$1
  readonly dir
  shift

  libs=$@
  readonly libs

  sst_am_distribute $dir/**/*.@(h|hpp)

  for x1 in \
    $dir/**/*.c \
    $dir/**/*.cpp \
  ; do

    expect_safe_path "$x1"

    x2=$(echo $x1 | sed 's/\.[^.]*$//')
    x3=$(echo $x2 | sed 's/[^A-Za-z0-9_]/_/g')

    cat >$x2.gitignorable.am <<EOF
##
## Copyright (C) 2021 Stealth Software Technologies, Inc.
##
## Permission is hereby granted, free of charge, to any person
## obtaining a copy of this software and associated documentation
## files (the "Software"), to deal in the Software without
## restriction, including without limitation the rights to use,
## copy, modify, merge, publish, distribute, sublicense, and/or
## sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following
## conditions:
##
## The above copyright notice and this permission notice shall be
## included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
## EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
## OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
## NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
## HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
## WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
## OTHER DEALINGS IN THE SOFTWARE.
##

##
## This file was generated by ./autogen.
##

## begin_variables

TESTS += $x2

check_PROGRAMS += $x2

${x3}_CFLAGS = \\
  \$(AM_CFLAGS) \\
  \$(EXE_CFLAGS) \\
\$(prevent_an_empty_line)

${x3}_CPPFLAGS = \\
  \$(AM_CPPFLAGS) \\
  -I $dir \\
  -I \$(srcdir)/$dir \\
\$(prevent_an_empty_line)

${x3}_CXXFLAGS = \\
  \$(AM_CXXFLAGS) \\
  \$(EXE_CXXFLAGS) \\
\$(prevent_an_empty_line)

${x3}_LDADD = $libs

${x3}_LDFLAGS = \\
  \$(AM_LDFLAGS) \\
  \$(EXE_LDFLAGS) \\
\$(prevent_an_empty_line)

${x3}_SOURCES = $x1

## end_variables
EOF

    sst_am_include $x2.gitignorable.am

  done

}; readonly -f sst_ajh_c_cpp_test
